/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "4.1.3-sophon-0.10.0-rc1-35-g7e1540b4a"
#endif /* AVUTIL_FFVERSION_H */
