/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "4.1.3-sophon-0.13.0-rc1-5-g2b877dbe4"
#endif /* AVUTIL_FFVERSION_H */
