/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "4.1.3-sophon-0.12.0-1-ga5cd8b405"
#endif /* AVUTIL_FFVERSION_H */
